version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flux_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: flux_db
      POSTGRES_USER: flux_user
      POSTGRES_PASSWORD: flux_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
